name: dbdumpexplr
base: core20
version: '0.1'
summary: Explore SQL database dumps in an offline environment.
description: |
  A conveinence tool to explore mysqldumps in a confined environment.
  `dbdumpexplr` provides an offline environment for importing, exploring and exporting a mysql databasedump.
grade: devel
confinement: strict

apps:
  dbdumpexplr:
    command: bin/dbdumpexplr.sh

parts:
  part-packages:
    plugin: nil
    stage-packages:
      - mysql-server
      - mysql-client

  part-dbdumpexplr:
    plugin: dump
    source: .
    organize:
      dbdumpexplr.sh: bin/

